# Generated by Django 5.1.4 on 2025-01-17 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="categories",
            field=models.ManyToManyField(
                related_name="recipes", to="recipes.category", verbose_name="Категории"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.IntegerField(verbose_name="Время приготовления (в минутах)"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="recipe_images/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="steps",
            field=models.TextField(verbose_name="Рецепт салата"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название рецепта"),
        ),
    ]
