# Generated by Django 5.1.4 on 2025-01-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_category_options_alter_recipe_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название салата"),
        ),
    ]
