# Generated by Django 5.1.4 on 2025-01-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_recipe_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название категории"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="categories",
            field=models.ManyToManyField(
                related_name="recipes", to="recipes.category", verbose_name="Категория"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="steps",
            field=models.TextField(verbose_name="Рецепт"),
        ),
    ]
